// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.12.3
// source: example/demo5.proto

package example

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Demo5Request_Gender int32

const (
	Demo5Request_MALE   Demo5Request_Gender = 0
	Demo5Request_FEMALE Demo5Request_Gender = 1
)

// Enum value maps for Demo5Request_Gender.
var (
	Demo5Request_Gender_name = map[int32]string{
		0: "MALE",
		1: "FEMALE",
	}
	Demo5Request_Gender_value = map[string]int32{
		"MALE":   0,
		"FEMALE": 1,
	}
)

func (x Demo5Request_Gender) Enum() *Demo5Request_Gender {
	p := new(Demo5Request_Gender)
	*p = x
	return p
}

func (x Demo5Request_Gender) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Demo5Request_Gender) Descriptor() protoreflect.EnumDescriptor {
	return file_example_demo5_proto_enumTypes[0].Descriptor()
}

func (Demo5Request_Gender) Type() protoreflect.EnumType {
	return &file_example_demo5_proto_enumTypes[0]
}

func (x Demo5Request_Gender) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Demo5Request_Gender.Descriptor instead.
func (Demo5Request_Gender) EnumDescriptor() ([]byte, []int) {
	return file_example_demo5_proto_rawDescGZIP(), []int{0, 0}
}

type Demo5Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string              `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Age  int32               `protobuf:"varint,2,opt,name=age,proto3" json:"age,omitempty"`
	Info *Demo5Request_Other `protobuf:"bytes,3,opt,name=info,proto3" json:"info,omitempty"`
}

func (x *Demo5Request) Reset() {
	*x = Demo5Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_example_demo5_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Demo5Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Demo5Request) ProtoMessage() {}

func (x *Demo5Request) ProtoReflect() protoreflect.Message {
	mi := &file_example_demo5_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Demo5Request.ProtoReflect.Descriptor instead.
func (*Demo5Request) Descriptor() ([]byte, []int) {
	return file_example_demo5_proto_rawDescGZIP(), []int{0}
}

func (x *Demo5Request) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Demo5Request) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *Demo5Request) GetInfo() *Demo5Request_Other {
	if x != nil {
		return x.Info
	}
	return nil
}

type Demo5Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Info string `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
}

func (x *Demo5Response) Reset() {
	*x = Demo5Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_example_demo5_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Demo5Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Demo5Response) ProtoMessage() {}

func (x *Demo5Response) ProtoReflect() protoreflect.Message {
	mi := &file_example_demo5_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Demo5Response.ProtoReflect.Descriptor instead.
func (*Demo5Response) Descriptor() ([]byte, []int) {
	return file_example_demo5_proto_rawDescGZIP(), []int{1}
}

func (x *Demo5Response) GetInfo() string {
	if x != nil {
		return x.Info
	}
	return ""
}

type Demo5Request_Other struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Addr  string              `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	Hobby string              `protobuf:"bytes,2,opt,name=hobby,proto3" json:"hobby,omitempty"`
	G     Demo5Request_Gender `protobuf:"varint,3,opt,name=g,proto3,enum=example.Demo5Request_Gender" json:"g,omitempty"`
}

func (x *Demo5Request_Other) Reset() {
	*x = Demo5Request_Other{}
	if protoimpl.UnsafeEnabled {
		mi := &file_example_demo5_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Demo5Request_Other) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Demo5Request_Other) ProtoMessage() {}

func (x *Demo5Request_Other) ProtoReflect() protoreflect.Message {
	mi := &file_example_demo5_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Demo5Request_Other.ProtoReflect.Descriptor instead.
func (*Demo5Request_Other) Descriptor() ([]byte, []int) {
	return file_example_demo5_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Demo5Request_Other) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Demo5Request_Other) GetHobby() string {
	if x != nil {
		return x.Hobby
	}
	return ""
}

func (x *Demo5Request_Other) GetG() Demo5Request_Gender {
	if x != nil {
		return x.G
	}
	return Demo5Request_MALE
}

var File_example_demo5_proto protoreflect.FileDescriptor

var file_example_demo5_proto_rawDesc = []byte{
	0x0a, 0x13, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2f, 0x64, 0x65, 0x6d, 0x6f, 0x35, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x22, 0xe4,
	0x01, 0x0a, 0x0c, 0x44, 0x65, 0x6d, 0x6f, 0x35, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x03, 0x61, 0x67, 0x65, 0x12, 0x2f, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x44, 0x65,
	0x6d, 0x6f, 0x35, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x4f, 0x74, 0x68, 0x65, 0x72,
	0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x1a, 0x5d, 0x0a, 0x05, 0x4f, 0x74, 0x68, 0x65, 0x72, 0x12,
	0x12, 0x0a, 0x04, 0x61, 0x64, 0x64, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x61,
	0x64, 0x64, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x68, 0x6f, 0x62, 0x62, 0x79, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x68, 0x6f, 0x62, 0x62, 0x79, 0x12, 0x2a, 0x0a, 0x01, 0x67, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x1c, 0x2e, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x44,
	0x65, 0x6d, 0x6f, 0x35, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x47, 0x65, 0x6e, 0x64,
	0x65, 0x72, 0x52, 0x01, 0x67, 0x22, 0x1e, 0x0a, 0x06, 0x47, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12,
	0x08, 0x0a, 0x04, 0x4d, 0x41, 0x4c, 0x45, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x46, 0x45, 0x4d,
	0x41, 0x4c, 0x45, 0x10, 0x01, 0x22, 0x23, 0x0a, 0x0d, 0x44, 0x65, 0x6d, 0x6f, 0x35, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x32, 0x7f, 0x0a, 0x05, 0x44, 0x65,
	0x6d, 0x6f, 0x35, 0x12, 0x3a, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x15,
	0x2e, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x44, 0x65, 0x6d, 0x6f, 0x35, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e,
	0x44, 0x65, 0x6d, 0x6f, 0x35, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x3a, 0x0a, 0x07, 0x53, 0x65, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x15, 0x2e, 0x65, 0x78, 0x61,
	0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x44, 0x65, 0x6d, 0x6f, 0x35, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x16, 0x2e, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x44, 0x65, 0x6d, 0x6f,
	0x35, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_example_demo5_proto_rawDescOnce sync.Once
	file_example_demo5_proto_rawDescData = file_example_demo5_proto_rawDesc
)

func file_example_demo5_proto_rawDescGZIP() []byte {
	file_example_demo5_proto_rawDescOnce.Do(func() {
		file_example_demo5_proto_rawDescData = protoimpl.X.CompressGZIP(file_example_demo5_proto_rawDescData)
	})
	return file_example_demo5_proto_rawDescData
}

var file_example_demo5_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_example_demo5_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_example_demo5_proto_goTypes = []interface{}{
	(Demo5Request_Gender)(0),   // 0: example.Demo5Request.Gender
	(*Demo5Request)(nil),       // 1: example.Demo5Request
	(*Demo5Response)(nil),      // 2: example.Demo5Response
	(*Demo5Request_Other)(nil), // 3: example.Demo5Request.Other
}
var file_example_demo5_proto_depIdxs = []int32{
	3, // 0: example.Demo5Request.info:type_name -> example.Demo5Request.Other
	0, // 1: example.Demo5Request.Other.g:type_name -> example.Demo5Request.Gender
	1, // 2: example.Demo5.GetInfo:input_type -> example.Demo5Request
	1, // 3: example.Demo5.SetName:input_type -> example.Demo5Request
	2, // 4: example.Demo5.GetInfo:output_type -> example.Demo5Response
	2, // 5: example.Demo5.SetName:output_type -> example.Demo5Response
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_example_demo5_proto_init() }
func file_example_demo5_proto_init() {
	if File_example_demo5_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_example_demo5_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Demo5Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_example_demo5_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Demo5Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_example_demo5_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Demo5Request_Other); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_example_demo5_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_example_demo5_proto_goTypes,
		DependencyIndexes: file_example_demo5_proto_depIdxs,
		EnumInfos:         file_example_demo5_proto_enumTypes,
		MessageInfos:      file_example_demo5_proto_msgTypes,
	}.Build()
	File_example_demo5_proto = out.File
	file_example_demo5_proto_rawDesc = nil
	file_example_demo5_proto_goTypes = nil
	file_example_demo5_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// Demo5Client is the client API for Demo5 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type Demo5Client interface {
	// 定义服务接口
	GetInfo(ctx context.Context, in *Demo5Request, opts ...grpc.CallOption) (*Demo5Response, error)
	SetName(ctx context.Context, in *Demo5Request, opts ...grpc.CallOption) (*Demo5Response, error)
}

type demo5Client struct {
	cc grpc.ClientConnInterface
}

func NewDemo5Client(cc grpc.ClientConnInterface) Demo5Client {
	return &demo5Client{cc}
}

func (c *demo5Client) GetInfo(ctx context.Context, in *Demo5Request, opts ...grpc.CallOption) (*Demo5Response, error) {
	out := new(Demo5Response)
	err := c.cc.Invoke(ctx, "/example.Demo5/GetInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *demo5Client) SetName(ctx context.Context, in *Demo5Request, opts ...grpc.CallOption) (*Demo5Response, error) {
	out := new(Demo5Response)
	err := c.cc.Invoke(ctx, "/example.Demo5/SetName", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Demo5Server is the server API for Demo5 service.
type Demo5Server interface {
	// 定义服务接口
	GetInfo(context.Context, *Demo5Request) (*Demo5Response, error)
	SetName(context.Context, *Demo5Request) (*Demo5Response, error)
}

// UnimplementedDemo5Server can be embedded to have forward compatible implementations.
type UnimplementedDemo5Server struct {
}

func (*UnimplementedDemo5Server) GetInfo(context.Context, *Demo5Request) (*Demo5Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInfo not implemented")
}
func (*UnimplementedDemo5Server) SetName(context.Context, *Demo5Request) (*Demo5Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetName not implemented")
}

func RegisterDemo5Server(s *grpc.Server, srv Demo5Server) {
	s.RegisterService(&_Demo5_serviceDesc, srv)
}

func _Demo5_GetInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Demo5Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Demo5Server).GetInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/example.Demo5/GetInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Demo5Server).GetInfo(ctx, req.(*Demo5Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Demo5_SetName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Demo5Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Demo5Server).SetName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/example.Demo5/SetName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Demo5Server).SetName(ctx, req.(*Demo5Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _Demo5_serviceDesc = grpc.ServiceDesc{
	ServiceName: "example.Demo5",
	HandlerType: (*Demo5Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetInfo",
			Handler:    _Demo5_GetInfo_Handler,
		},
		{
			MethodName: "SetName",
			Handler:    _Demo5_SetName_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "example/demo5.proto",
}
